name: 'Publish SemVer Docker tags'
description: 'Tag and publish a Docker image according to Semantic Versioning'
author: 'Flownative'
inputs:
  tag_ref:
    description: 'The full tag reference. This must be a semver tag ref of an existing tagged image. For example, `refs/tags/v1.2.5-12`'
    required: true
    default: ''
  tag_latest:
    description: 'If a "latest" tag should also be created and published. Must be non-empty for "yes" and empty for "no"'
    required: false
    default: 'true'
  tag_strip_v_prefix:
    description: 'If the "v" prefix should be removed from a tag before using it for tagging a Docker image. Must be non-empty for "yes" and empty for "no"'
    required: false
    default: 'true'
  source_image_name:
    description: 'The full source image name (to be built), without tag. For example, `docker.pkg.github.com/flownative/docker-magic-image/magic-image`'
    required: true
    default: ''
  source_registry_username:
    description: 'Username for the source registry'
    required: true
    default: ''
  source_registry_password:
    description: 'Password for the source registry'
    required: true
    default: ''
  source_registry_endpoint:
    description: 'Endpoint of the source registry. For example, `https://docker.pkg.github.com/v2/`'
    required: false
    default: 'https://docker.pkg.github.com/v2/'
  target_image_name:
    description: 'The full target image name, without tag. For example, `docker.io/flownative/magic-image`'
    required: true
    default: ''
  target_registry_username:
    description: 'Username for the target registry'
    required: true
    default: ''
  target_registry_password:
    description: 'Password for the target registry'
    required: true
    default: ''
  target_registry_endpoint:
    description: 'Endpoint of the target registry. For example, `https://index.docker.io/v1/`'
    required: false
    default: 'https://index.docker.io/v1/'

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'package'
  color: 'blue'
