name: 'Publish SemVer Docker tags'
description: 'Tag and publish a Docker image according to Semantic Versioning'
author: 'Flownative'
inputs:
  github_package_name:
    description: 'The full Github package (docker image) name. For example, `flownative/docker-magic-image/magic-image`'
    required: true
    default: ''
  tag:
    description: 'The full tag. This must be a semver tag of an existing tagged image. For example, `v1.2.5-12`'
    required: true
    default: ''
  target_image_name:
    description: 'The full target image name, without tag. For example, `docker.io/flownative/magic-image`'
    required: true
    default: ''
  target_registry_username:
    description: 'Username for the target registry'
    required: true
    default: ''
  target_registry_password:
    description: 'Password for the target registry'
    required: true
    default: ''
  target_registry_endpoint:
    description: 'Endpoint of the target registry. For example, `https://index.docker.io/v1/`'
    required: false
    default: 'https://index.docker.io/v1/'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'package'
  color: 'blue'
